name: eks
path: modules/core/eks/
parameters:
  - name: vpc-id
    valueFrom:
      moduleMetadata:
        group: optionals
        name: networking
        key: VpcId
  - name: private-subnet-ids
    valueFrom:
      moduleMetadata:
        group: optionals
        name: networking
        key: PrivateSubnetIds
  - name: eks-admin-role-name
    value: Admin
  - name: eks-poweruser-role-name
    value: PowerUser
  - name: eks-read-only-role-name
    value: ReadOnly
  - name: eks-version
    valueFrom:
      envVariable: GLOBAL_EKS_VERSION
  - name: eks-compute
    value:
      eks_nodegroup_config:
        - eks_ng_name: ng1
          eks_node_quantity: 3
          eks_node_max_quantity: 6
          eks_node_min_quantity: 2
          eks_node_disk_size: 50
          eks_node_instance_types:
            - "m5.large"
        - eks_ng_name: ng2
          eks_node_quantity: 3
          eks_node_max_quantity: 6
          eks_node_min_quantity: 2
          eks_node_disk_size: 50
          eks_node_instance_types:
            - "m5.xlarge"
        - eks_ng_name: gpung1
          eks_node_quantity: 1
          eks_node_max_quantity: 3
          eks_node_min_quantity: 1
          eks_node_disk_size: 100
          eks_node_instance_types:
            - "g4dn.xlarge"
          eks_node_labels:
            usage: visualization
      eks_node_spot: False
      eks_api_endpoint_private: False
  - name: eks-addons
    value:
      deploy_aws_lb_controller: True # We deploy it unless set to False
      deploy_external_dns: True # We deploy it unless set to False
      deploy_aws_ebs_csi: True # We deploy it unless set to False
      deploy_aws_efs_csi: True # We deploy it unless set to False
      deploy_cluster_autoscaler: True # We deploy it unless set to False
      deploy_metrics_server: True # We deploy it unless set to False
      deploy_secretsmanager_csi: True # We deploy it unless set to False
      deploy_cloudwatch_container_insights_metrics: True # We deploy it unless set to False
      deploy_cloudwatch_container_insights_logs: True
      cloudwatch_container_insights_logs_retention_days: 7
      deploy_kured: False
      deploy_calico: False
      deploy_nginx_controller: False
      nginx_additional_annotations:
        nginx.ingress.kubernetes.io/whitelist-source-range: "100.64.0.0/10,10.0.0.0/8"
      deploy_kyverno: False
      kyverno_policies:
        validate:
          - block-ephemeral-containers
          - block-stale-images
          - block-updates-deletes
          - check-deprecated-apis
          - disallow-cri-sock-mount
          - disallow-custom-snippets
          - disallow-empty-ingress-host
          - disallow-helm-tiller
          - disallow-latest-tag
          - disallow-localhost-services
          - disallow-secrets-from-env-vars
          - ensure-probes-different
          - ingress-host-match-tls
          - limit-hostpath-vols
          - prevent-naked-pods
          - require-drop-cap-net-raw
          - require-emptydir-requests-limits
          - require-labels
          - require-pod-requests-limits
          - require-probes
          - restrict-annotations
          - restrict-automount-sa-token
          - restrict-binding-clusteradmin
          - restrict-clusterrole-nodesproxy
          - restrict-escalation-verbs-roles
          - restrict-ingress-classes
          - restrict-ingress-defaultbackend
          - restrict-node-selection
          - restrict-path
          - restrict-service-external-ips
          - restrict-wildcard-resources
          - restrict-wildcard-verbs
          - unique-ingress-host-and-path
        # mutate:
        #   - add-networkpolicy-dns
        #   - add-pod-priorityclassname
        #   - add-ttl-jobs
        #   - always-pull-images
        #   - mitigate-log4shell
---
name: efs
path: modules/core/efs
targetAccount: primary
targetRegion: us-east-1
parameters:
  - name: vpc-id
    valueFrom:
      moduleMetadata:
        group: optionals
        name: networking
        key: VpcId
  - name: removal-policy
    value: DESTROY
